In [4]:
import pandas as pd
df1 = pd.read_csv("idle.csv", index_col=[0])
df1.drop(columns = 'Config', inplace = True)
df2 = pd.read_csv('mali.csv',  index_col=[0])
df1.reset_index(inplace = True)
df2.reset_index(inplace = True)
df1.drop(columns='index', inplace = True)
df2.drop(columns='index', inplace =True)
df2.columns = ['App', 'GPU_Freq', 'Dev', 'Total_Acumulada', 'GPU_Acumulada',
       'A15_Acumulada', 'A7_Acumulada', 'MEM_Acumulada', 'real', 'sys', 'user',
       'EDP', 'A15_Power', 'A7_Power', 'MEM_Power', 'GPU_Power', 'Type']
df2['Host'] = "A15"
df2['A15_Freq'] = '1'
df2['A7_Freq'] = '1'
col = df2['A7_Freq']
df2.drop(labels=['A7_Freq'], axis=1,inplace = True)
df2.insert(0, 'A7_Freq', col)
col = df2['A15_Freq']
df2.drop(labels=['A15_Freq'], axis=1,inplace = True)
df2.insert(0, 'A15_Freq', col)
col = df2['Dev']
df2.drop(labels=['Dev'], axis=1,inplace = True)
df2.insert(0, 'Dev', col)
col = df2['Host']
df2.drop(labels=['Host'], axis=1,inplace = True)
df2.insert(0, 'Host', col)
col = df2['App']
df2.drop(labels=['App'], axis=1,inplace = True)
df2.insert(0, 'App', col)


col = df1['GPU_Acumulada']
df1.drop(labels=['GPU_Acumulada'], axis=1,inplace = True)
df1.insert(0, 'GPU_Acumulada', col)
col = df1['Total_Acumulada']
df1.drop(labels=['Total_Acumulada'], axis=1,inplace = True)
df1.insert(0, 'Total_Acumulada', col)
col = df1['GPU_Freq']
df1.drop(labels=['GPU_Freq'], axis=1,inplace = True)
df1.insert(0, 'GPU_Freq', col)
col = df1['A7_Freq']
df1.drop(labels=['A7_Freq'], axis=1,inplace = True)
df1.insert(0, 'A7_Freq', col)
col = df1['A15_Freq']
df1.drop(labels=['A15_Freq'], axis=1,inplace = True)
df1.insert(0, 'A15_Freq', col)
col = df1['Dev']
df1.drop(labels=['Dev'], axis=1,inplace = True)
df1.insert(0, 'Dev', col)
col = df1['Host']
df1.drop(labels=['Host'], axis=1,inplace = True)
df1.insert(0, 'Host', col)
col = df1['App']
df1.drop(labels=['App'], axis=1,inplace = True)
df1.insert(0, 'App', col)

In [5]:
df1.head(2)

,App,Host,Dev,A15_Freq,A7_Freq,GPU_Freq,Total_Acumulada,GPU_Acumulada,A15_Acumulada,A7_Acumulada,MEM_Acumulada,real,sys,user,EDP,A15_Power,A7_Power,MEM_Power,GPU_Power,Type
0,3DCONV,A15,A15,1,1,0.6,3.466471,0.173647,2.688219,0.249904,0.354700,2.4941,0.9888,1.4260,8.645725,1.077831,0.100198,0.142216,0.069623,Convolution
1,3MM,A15,A15,1,1,0.6,6.140845,0.340621,5.316578,0.240441,0.243205,3.3140,0.1789,10.5086,20.350760,1.604278,0.072553,0.073387,0.102782,Linear Algebra

In [3]:
df2.head(2)

,App,Host,Dev,A15_Freq,A7_Freq,GPU_Freq,Total_Acumulada,GPU_Acumulada,A15_Acumulada,A7_Acumulada,MEM_Acumulada,real,sys,user,EDP,A15_Power,A7_Power,MEM_Power,GPU_Power,Type
0,2DCONV,A15,GPU,1,1,1.77,10.947489,0.337780,3.403971,0.413798,0.596306,6.195633,1.091633,4.707400,67.826627,0.549415,0.066789,0.096246,0.054519,Convolution
1,2DCONV,A15,GPU,1,1,2.66,10.378181,0.292762,3.129412,0.378646,0.526093,6.051267,1.045933,4.704767,62.801139,0.517150,0.062573,0.086939,0.048380,Convolution